-- EX1
SELECT NAME FROM CITY 
WHERE POPULATION > 120000 AND COUNTRYCODE = 'USA' 
--EX2
SELECT * FROM CITY
WHERE COUNTRYCODE ='JPN'
--EX3
SELECT CITY, STATE FROM STATION
--EX4
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%' 
-- CÁCH 2 EX4
SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou]'
--EX5 
SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '[aeiou]$'
--EX6
SELECT DISTINCT CITY FROM STATION
WHERE  NOT CITY REGEXP '^[ueoai]'
--EX7
SELECT name FROM Employee
ORDER BY name 
--EX8
SELECT name FROM Employee 
Where salary > 2000 and months < 10 
Order by employee_id 
--EX9
SELECT product_id FROM products 
WHERE low_fats = 'Y' AND recyclable = 'Y'
--EX10
SELECT name FROM Customer
WHERE NOT referee_id = 2 OR referee_id is null
--EX11
SELECT name, population, area FROM World
WHERE area >= 3000000 OR population >= 25000000
